service: serverless-webpack-typescript-example
package:
  individually: true
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1

functions:
  hello:
    handler: src/handler.graphqlHandler
    events:
      - http:
          method: get
          path: hello
          integration: lambda
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules: true

  serverless-offline:
    port: 4000
